# https://github.com/psf/black
[tool.black]
target-version = ["py39"]
color = false
line-length = 120

exclude = '''
/(
    \.git
    | \.mypy_cache
    | \.tox
    | \.venv
    | build
    | venv
)/
'''

[tool.mypy]
mypy_path = "monolg"
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true
warn_unreachable = true
# check_untyped_defs = false
# disallow_any_generics = true
# ignore_missing_imports = true
# no_implicit_optional = true
# show_error_codes = true
# strict_equality = true
# warn_redundant_casts = true
# warn_return_any = true
# warn_unreachable = true
# warn_unused_configs = true
# no_implicit_reexport = true


[tool.pytest.ini_options]
addopts = [
  "--ignore=tests/test_monolg.py"
]
filterwarnings = [
    "ignore::DeprecationWarning"
]
markers = [
    "schema      : Schema related tests",
    "configs     : Tests for all available config keys",
    "utils       : Utility tests",
    "monolg      : Tests for the Monolg class",
    "unavailable : MongoDB is unavailable",
    "available   : MongoDB is available"
]
